version: '3'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
    - 4444:4444
    logging:
      driver: none
    shm_size: '1gb'
    restart: always

  scrapper:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
    - ./app:/app
    ports:
      - 5000:5000
    command: sh -c "python3 scrapper.py"
    depends_on:
    - selenium